# Generated by Django 4.1.3 on 2022-11-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedsecret',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_secrets', to='features.vault'),
        ),
        migrations.AddField(
            model_name='sharedsecret',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_secrets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lockkey',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock_key', to='features.vault'),
        ),
    ]
