# Generated by Django 4.1.3 on 2022-11-10 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.FileField(upload_to='public-keys/file/')),
                ('private_key', models.FileField(upload_to='private-keys/file/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_pair', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
