# Generated by Django 4.1.3 on 2022-11-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0003_rsakeypair'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='signed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rsakeypair',
            name='private_key',
            field=models.FileField(upload_to='file/private-keys/'),
        ),
        migrations.AlterField(
            model_name='rsakeypair',
            name='public_key',
            field=models.FileField(upload_to='file/public-keys/'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='document',
            field=models.FileField(upload_to='file/encrypted'),
        ),
    ]
